# Notebook 01: Data Extraction

In this notebook, we load the raw data and prove that it passes the **Capstone 2 Minimum Standards** (At least 5,000 rows and 8 meaningful analytical columns). We are not altering or cleaning any data here.

### Step 1: Import Libraries

In [2]:
import pandas as pd

### Step 2: Load the Raw Dataset
Loading the completely untouched raw data from our `data/raw/` directory.

In [3]:
# Load dataset
df = pd.read_csv("../data/raw/Banking_churn_prediction.csv")

# Show first 5 rows
df.head()

,customer_id,vintage,age,gender,dependents,occupation,city,customer_nw_category,branch_code,current_balance,...,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance,churn,last_transaction
0,1,2101,66,Male,0.0,self_employed,187.0,2,755,1458.71,...,1458.71,1449.07,0.20,0.20,0.20,0.20,1458.71,1458.71,0,2019-05-21
1,2,2348,35,Male,0.0,self_employed,NaN,2,3214,5390.37,...,7799.26,12419.41,0.56,0.56,5486.27,100.56,6496.78,8787.61,0,2019-11-01
2,4,2194,31,Male,0.0,salaried,146.0,2,41,3913.16,...,4910.17,2815.94,0.61,0.61,6046.73,259.23,5006.28,5070.14,0,NaT
3,5,2329,90,NaN,NaN,self_employed,1020.0,2,582,2291.91,...,2084.54,1006.54,0.47,0.47,0.47,2143.33,2291.91,1669.79,1,2019-08-06
4,6,1579,42,Male,2.0,self_employed,1494.0,3,388,927.72,...,1643.31,1871.12,0.33,714.61,588.62,1538.06,1157.15,1677.16,1,2019-11-03

### Step 3: Check Capstone 2 Requirements
We need to prove to the evaluator that our dataset is large enough! Minimum Requirements: 5,000 rows and 8 columns.

In [10]:
# Get number of rows and columns
rows = df.shape[0]
cols = df.shape[1]

print("Total Rows:", rows)
print("Total Columns:", cols)

# Check requirements
if rows >= 5000:
    print("Dataset meets row requirement")
else:
    print("Dataset does NOT meet row requirement")

if cols >= 8:
    print("Dataset meets column requirement")
else:
    print("Dataset does NOT meet column requirement")

Total Rows: 28382
Total Columns: 21
Dataset meets row requirement
Dataset meets column requirement

### Step 4: Dataset Info
We investigate numeric vs categorical datatypes.

In [5]:
# Check data types and null values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28382 entries, 0 to 28381
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   customer_id                     28382 non-null  int64
 1   vintage                         28382 non-null  int64
 2   age                             28382 non-null  int64
 3   gender                          27857 non-null  str
 4   dependents                      25919 non-null  float64
 5   occupation                      28302 non-null  str
 6   city                            27579 non-null  float64
 7   customer_nw_category            28382 non-null  int64
 8   branch_code                     28382 non-null  int64
 9   current_balance                 28382 non-null  float64
 10  previous_month_end_balance      28382 non-null  float64
 11  average_monthly_balance_prevQ   28382 non-null  float64
 12  average_monthly_balance_prevQ2  28382 non-null  float64
 13  current_month_credit            28382 non-null  float64
 14  previous_month_credit           28382 non-null  float64
 15  current_month_debit             28382 non-null  float64
 16  previous_month_debit            28382 non-null  float64
 17  current_month_balance           28382 non-null  float64
 18  previous_month_balance          28382 non-null  float64
 19  churn                           28382 non-null  int64
 20  last_transaction                28382 non-null  str
dtypes: float64(12), int64(6), str(3)
memory usage: 4.5 MB

### Step 5: Dataset Summary (Describe)
We look at the basic statistics (mean, min, max, etc.) for our numerical columns.

In [6]:
# Summary of numerical columns
df.describe()

,customer_id,vintage,age,dependents,city,customer_nw_category,branch_code,current_balance,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance,churn
count,28382.000000,28382.000000,28382.000000,25919.000000,27579.000000,28382.000000,28382.000000,2.838200e+04,2.838200e+04,2.838200e+04,2.838200e+04,2.838200e+04,2.838200e+04,2.838200e+04,2.838200e+04,2.838200e+04,2.838200e+04,28382.000000
mean,15143.508667,2091.144105,48.208336,0.347236,796.109576,2.225530,925.975019,7.380552e+03,7.495771e+03,7.496780e+03,7.124209e+03,3.433252e+03,3.261694e+03,3.658745e+03,3.339761e+03,7.451133e+03,7.495177e+03,0.185329
std,8746.454456,272.676775,17.807163,0.997661,432.872102,0.660443,937.799129,4.259871e+04,4.252935e+04,4.172622e+04,4.457581e+04,7.707145e+04,2.968889e+04,5.198542e+04,2.430111e+04,4.203394e+04,4.243198e+04,0.388571
min,1.000000,73.000000,1.000000,0.000000,0.000000,1.000000,1.000000,-5.503960e+03,-3.149570e+03,1.428690e+03,-1.650610e+04,1.000000e-02,1.000000e-02,1.000000e-02,1.000000e-02,-3.374180e+03,-5.171920e+03,0.000000
25%,7557.250000,1958.000000,36.000000,0.000000,409.000000,2.000000,176.000000,1.784470e+03,1.906000e+03,2.180945e+03,1.832507e+03,3.100000e-01,3.300000e-01,4.100000e-01,4.100000e-01,1.996765e+03,2.074407e+03,0.000000
50%,15150.500000,2154.000000,46.000000,0.000000,834.000000,2.000000,572.000000,3.281255e+03,3.379915e+03,3.542865e+03,3.359600e+03,6.100000e-01,6.300000e-01,9.193000e+01,1.099600e+02,3.447995e+03,3.465235e+03,0.000000
75%,22706.750000,2292.000000,60.000000,0.000000,1096.000000,3.000000,1440.000000,6.635820e+03,6.656535e+03,6.666887e+03,6.517960e+03,7.072725e+02,7.492350e+02,1.360435e+03,1.357553e+03,6.667958e+03,6.654693e+03,0.000000
max,30301.000000,2476.000000,90.000000,52.000000,1649.000000,3.000000,4782.000000,5.905904e+06,5.740439e+06,5.700290e+06,5.010170e+06,1.226985e+07,2.361808e+06,7.637857e+06,1.414168e+06,5.778185e+06,5.720144e+06,1.000000

### Step 6: Identify Missing Values
We check exactly how many null values the ETL team needs to clean in the next step.

In [7]:
# Count missing values in each column
df.isnull().sum()

customer_id                          0
vintage                              0
age                                  0
gender                             525
dependents                        2463
occupation                          80
city                               803
customer_nw_category                 0
branch_code                          0
current_balance                      0
previous_month_end_balance           0
average_monthly_balance_prevQ        0
average_monthly_balance_prevQ2       0
current_month_credit                 0
previous_month_credit                0
current_month_debit                  0
previous_month_debit                 0
current_month_balance                0
previous_month_balance               0
churn                                0
last_transaction                     0
dtype: int64

### Step 7: Identify Duplicate Values
We check exactly how many duplicate values does the dataset have

In [9]:
df.duplicated().sum()

np.int64(0)

### Extraction Complete.
Our dataset passes the required checks. We will handle the missing values seen above in our next notebook: **`02_cleaning.ipynb`**.